### ISSUE TITLE
Checkbox Needs Indeterminate State

### ISSUE THREAD

**Issue by Bates550** [procore/core#295]
### Issue Summary:
- The [`Checkbox` component](https://procore.github.io/core/latest/react/#!/Checkbox) does not support an [indeterminate state](https://css-tricks.com/indeterminate-checkboxes/).

### Proposal:

Following this [blog post on the topic](http://webroo.org/articles/2016-02-10/indeterminate-checkboxes-in-react/): add an `indeterminate` prop that takes precedence over the `checked` prop.
```jsx
/* Renders indeterminate */
<Checkbox indeterminate={true} checked={true} /> 

/* Renders checked */
<Checkbox indeterminate={false} checked={true} /> 
```

**Comment by brock-noah** [comment]
*precedence over the checked UI

> The indeterminate state is visual only. The checkbox is still either checked or unchecked as a state.

I think the indeterminate should not effect the checked value of the box. That is up to the client app.

**Comment by brock-noah** [comment]
Also since the article Sean linked uses `ref`, it would be nice if this PR handled passing a ref to the checkbox  like how we had to do with input
`<Checkbox checkboxRef={(ref) => } />`

**Comment by Bates550** [comment]
@brock-noah I agree with indeterminate not affecting the checked state. Not sure where you're quoting from though.

What's the use case for the ref? It seems like that is an implementation detail of the Checkbox.

**Comment by brock-noah** [comment]
I'm quoting from the CSS tricks article.

For `ref` the following code is broken because the ref is attached to a React instance and not an actual DOM node.
```
<Checkbox ref={ref => this.boxRef = ref} />
this.boxRef.focus()
```
You could do `ReactDOM.findDOMNode(this.boxRef)` but according to the React Docs `findDOMNode` is discouraged.

More detail [from React docs](https://reactjs.org/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components). Input PR https://github.com/procore/core/pull/274

**Comment by Bates550** [comment]
Is that related to indeterminate state or just something else we'd like on the Checkbox?

**Comment by brock-noah** [comment]
Really it is something else. It's only related to indeterminate state because they both deal with refs. Thought I'd mention it because they both need to be done.

**Comment by Bates550** [comment]
Looks slick. Thanks guys!
