### ISSUE TITLE
Clickable or not

### ISSUE THREAD

**Issue by brock-noah** [procore/core#340]
### Issue Summary:
- Avatar CSS by default includes `pointer: cursor`

### Proposal:
- make it not clickable by default to match icons
- use `.core-clickable` to add this state to items that need it

### Discussion Topics:
- this would be a breaking change. we should bundle small changes like these together

**Comment by janamcclure** [comment]
I support this change.

**Comment by janamcclure** [comment]
https://procoretech.atlassian.net/browse/GLUE-303
