### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by brock-noah** [procore/core#341]
### Issue Summary:
- Core React is missing a header component

### Proposal / Discussion Topics:
A) `<Header type='1'>For an H1</Header>`
B) `<H1>For an H1</H1>`

**Comment by janamcclure** [comment]
https://procoretech.atlassian.net/browse/GLUE-304

**Comment by janamcclure** [comment]
https://procoretech.atlassian.net/browse/GLUE-307
