### ISSUE TITLE
Icon Cursor

### ISSUE THREAD

**Issue by brock-noah** [procore/core#345]
### Issue Summary:
- Icon applies `cursor: text`. I have a parent that applies a different cursor. This should cascade to the Icon.

Was there a specific reason this is specified?

### Proposal:
- Delete this line https://github.com/procore/core/blob/develop/packages/core-react/src/components/Icon/Icon.js#L75
- I would also like to delete this file https://github.com/procore/core/blob/master/packages/core-css/src/components/_icon.scss and make a util `core-clickable`

**Comment by mboperator** [comment]
Spoke w/ Brock offline. This seems like a UX issue in general so we should tackle this before the end of the year.

**Comment by janamcclure** [comment]
https://procoretech.atlassian.net/browse/GLUE-309

**Comment by janamcclure** [comment]
https://procoretech.atlassian.net/browse/GLUE-310 for avatar
