### ISSUE TITLE
Missing CSS Modules Binding

### ISSUE THREAD

**Issue by brock-noah** [procore/core#349]
### Issue Summary:
React components still reference global CSS
- banner__dismiss
- checkbox
- grid
- radio button
- tooltip__title

**Comment by mboperator** [comment]
`banner__dismiss` was solved and merged last week, and `grid` has just been tackled by @remyyounes.

The rest are the result of empty styles. When the class is empty, CSS Modules doesn't mangle the class. Closing when #357 is merged.

**Comment by farism** [comment]
Another question is... should we even add the `className` if there are no styles?
