### ISSUE TITLE
Checkbox and Radio Button Cursor

### ISSUE THREAD

**Issue by brock-noah** [procore/core#350]
### Issue Summary:
Checkboxes and radio buttons do not have a pointer cursor.
Natively these elements do not have one, but I feel like they should.

### Discussion Topics:
- [ ] Ask UI should these have points

**Comment by remyyounes** [comment]
If I recall correctly we've discussed this not too long ago and decided to stick with the native behavior as you pointed out. maybe @janamcclure can chime in?
I personally don't feel strongly about it but I would rather follow a convention that has been set for the sake of consistency.

**Comment by farism** [comment]
It looks like UX wants to stay firm on no pointer cursor for input controls.
