### ISSUE TITLE
foundation-sites dependency

### ISSUE THREAD

**Issue by brock-noah** [procore/core#362]
### Issue Summary:
`core-css` ships with `foundation-sites`. This is a [hefty dependency](https://bundlephobia.com/result?p=foundation-sites@6.4.4-rc1), 203kB. A client will download this unused dependecy, possibly several times if they are using several particles that use `core-react`

### Proposal
Separate documentation (`foundation-sites`, `react`, `react-dom`) from `core-css`.

**Comment by farism** [comment]
It's being used here.

https://github.com/procore/core/blob/develop/packages/core-css/src/core.scss#L44

I wouldn't mind using a different grid implementation.

**Comment by mboperator** [comment]
We settled on the Foundation grid implementation because it allowed us to easily adjust gutter sizes per viewport width. I like the API.

Another option is to just pull out their grid SCSS files into core css
https://github.com/zurb/foundation-sites/tree/develop/scss/grid

**Comment by mboperator** [comment]
I did a quick spike and it looks like the assumption is unfounded:
## With Foundation

<img width="357" alt="screen shot 2017-12-19 at 12 39 52 pm" src="https://user-images.githubusercontent.com/1007233/34177806-c538f3f4-e4b9-11e7-9b08-e8cf90012803.png">

## Without Foundation
<img width="387" alt="screen shot 2017-12-19 at 12 37 40 pm" src="https://user-images.githubusercontent.com/1007233/34177802-c22bc4b6-e4b9-11e7-9066-bfdb864cddf9.png">

**Comment by brock-noah** [comment]
If it's that small of a change we should probably keep the package over copying the code.

Dare I say, `core-grid`? Separate it completely. (but then we would have to make `core-react-grid`, `core-ruby-grid`)

I made this issue for particles consuming `core-react`. For wanting 2-3 styled components we get a lot. It's been mentioned before, but maybe individual exports for CSS and tree shaking on the consumer.

Maybe this is all nonsense, but I made the issue when I thought it was for documentation. Probably not a pressing issue.

**Comment by farism** [comment]
We were discussing extracting foundation sites and pulling it into core-css, but apparently foundation sites requires pulling in a LOT of `*.scss` files for the imports to work correctly. So now we are considering either

1) Writing our own grid system
2) Copy/paste in a simpler flex grid system

Closing this for now, any work to address this we will groom out.

**Comment by brock-noah** [comment]
What about [`display: grid`](https://caniuse.com/#feat=css-grid) ?
