### ISSUE TITLE
Publish source (each file individually) to NPM

### ISSUE THREAD

**Issue by dannyphillips** [procore/core#44]
We must have semver on each .css file, since any change will likely cause breaking changes in many apps.

**Comment by mboperator** [comment]
Do we still want to do this?

**Comment by remyyounes** [comment]
I don't think so.

**Comment by farism** [comment]
I think with Percy regression testing something like this won't be necessary (at least for testing purposes). Feel free to re-open if we have a compelling reason to justify the effort.
