### ISSUE TITLE
Avatar Hover

### ISSUE THREAD

**Issue by brock-noah** [procore/core#453]
### Issue Summary:
- forced hover state for `Avatar.Portrait`
- no hover states for `Avatar.Icon` `Avatar.Label`

### Proposal:
- no hover state by default
- have a hover state for all Avatars [confirm UX]

### Discussion Topics:
- [confirm UX] are clickable and hoverable the same thing?

**Comment by remyyounes** [comment]
I believe that hoverable and clickable are different

**Comment by janamcclure** [comment]
A hover state should be used to imply that an avatar is clickable. If a portrait is not clickable, it should not have a hover state. The same should be true of all avatars. All avatars should default to non clickable imo for consistency.

**Comment by janamcclure** [comment]
I am working on cleaning up the avatar specs with the ui team, you can see the latest progress here: https://procore.invisionapp.com/d/main#/console/12113821/256022493/comments

**Comment by farism** [comment]
https://github.com/procore/core/pull/619
